#!/usr/bin/env python3

"""
Create Outlook draft emails from an HTML email merge CSV.

Expected CSV columns:
- To
- Subject
- HTMLBody

Example:
    python src/send_outlook_drafts.py Consolidated_Grades_HTML_Email_Merge.csv --limit 2
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import tkinter as tk
from tkinter import filedialog

import pandas as pd


REQUIRED_COLUMNS = ["To", "Subject", "HTMLBody"]


def load_email_merge(csv_path: Path) -> pd.DataFrame:
    """Load and validate the email merge CSV."""
    df = pd.read_csv(csv_path)
    missing = [column for column in REQUIRED_COLUMNS if column not in df.columns]
    if missing:
        raise ValueError(
            f"Missing required column(s): {', '.join(missing)}. "
            f"Found columns: {', '.join(map(str, df.columns))}"
        )

    for column in REQUIRED_COLUMNS:
        df[column] = df[column].fillna("").astype(str)

    df = df[df["To"].str.strip() != ""].copy()
    if df.empty:
        raise ValueError("No rows with a recipient email were found in the CSV.")

    return df


def get_outlook_application():
    """Return the Outlook COM application."""
    try:
        import pythoncom  # type: ignore
        import win32com.client  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "pywin32 is required for Outlook draft creation. "
            "Install it with: pip install pywin32"
        ) from exc

    try:
        pythoncom.CoInitialize()
        outlook = win32com.client.gencache.EnsureDispatch("Outlook.Application")
        outlook.GetNamespace("MAPI")
        return outlook
    except Exception as exc:  # pragma: no cover - depends on local Outlook install
        raise RuntimeError(
            "Could not connect to Outlook. Make sure Outlook is installed, configured, "
            f"and can open normally. Underlying error: {exc}"
        ) from exc


def create_drafts(df: pd.DataFrame, *, limit: int | None = None) -> int:
    """Create Outlook draft messages from the dataframe."""
    outlook = get_outlook_application()
    rows = df.head(limit) if limit is not None else df

    created = 0
    for _, row in rows.iterrows():
        mail = outlook.CreateItem(0)
        mail.To = row["To"].strip()
        mail.Subject = row["Subject"].strip()
        mail.HTMLBody = row["HTMLBody"]
        mail.Save()
        created += 1

    return created


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create Outlook drafts from an HTML email merge CSV."
    )
    parser.add_argument(
        "csv_path",
        type=Path,
        nargs="?",
        help="Path to the HTML email merge CSV generated by gui_launcher.py",
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Create drafts for only the first N rows. Useful for testing with 1-2 emails.",
    )
    return parser


def pick_csv_file() -> Path | None:
    """Open a GUI file picker for the HTML email merge CSV."""
    root = tk.Tk()
    root.withdraw()
    path = filedialog.askopenfilename(
        title="Select the HTML email merge CSV",
        filetypes=[("CSV files", "*.csv"), ("All files", "*.*")],
    )
    root.destroy()
    return Path(path) if path else None


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()

    try:
        csv_path = args.csv_path or pick_csv_file()
        if csv_path is None:
            print("Error: no CSV file selected.", file=sys.stderr)
            return 1

        email_merge = load_email_merge(csv_path)
        created = create_drafts(email_merge, limit=args.limit)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1

    suffix = f" (limited to first {args.limit})" if args.limit is not None else ""
    print(f"Created {created} Outlook draft(s){suffix}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
